# Generated by Django 4.1.4 on 2023-08-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projecttype_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
