# Generated by Django 4.1.4 on 2023-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projecttype_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='image',
            field=models.TextField(),
        ),
    ]
