version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc-letsencrypt:/etc/letsencrypt
      - certbot-var-lib-letsencrypt:/var/lib/letsencrypt
      - nginx_conf:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
#    command: gunicorn portfolio.wsgi -b 0.0.0.0:8000
    environment:
      - "ENVIRONMENT=production"
      - "SECRET_KEY=izs#0gbfl-*12cq%p&d^^5^ac^o#+ag5f8_k&e^bk5-ku^m=9@"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
  certbot-etc-letsencrypt:
  certbot-var-lib-letsencrypt:
  nginx_conf:
