version: '3.3'

services:

  web:
    build: .
#    command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn portfolio.wsgi -b 0.0.0.0:8000
    environment:
      - "SECRET_KEY=izs#0gbfl-*12cq%p&d^^5^ac^o#+ag5f8_k&e^bk5-ku^m=9@"
      - "ENVIRONMENT=production"
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - webnet
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/code/static:ro
      - media_volume:/code/media:ro
      - nginx_conf:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc-letsencrypt:/etc/letsencrypt
      - certbot-var-lib-letsencrypt:/var/lib/letsencrypt
      - nginx_conf:/etc/nginx/conf.d
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ulugbekmuslitdinov@gmail.com --agree-tos --no-eff-email --force-renewal -d umuslitdinov.dev
    networks:
    - webnet


networks:
  webnet:
    driver: bridge

volumes:
  static_volume:
  postgres_data:
  certbot-etc-letsencrypt:
  certbot-var-lib-letsencrypt:
  nginx_conf:
  media_volume: