version: '3.3'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc-letsencrypt:/etc/letsencrypt
      - certbot-var-lib-letsencrypt:/var/lib/letsencrypt
    environment:
      - DOMAIN=umuslitdinov.dev
      - EMAIL=ulugbekmuslitdinov@gmail.com
    command: certbot certonly --webroot -w /var/www/certbot
    depends_on:
      - nginx
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc-letsencrypt:/etc/letsencrypt
      - nginx_conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build: .
    command: gunicorn portfolio.wsgi -b 0.0.0.0:8000
    environment:
      - "ENVIRONMENT=development"
      - "SECRET_KEY=izs#0gbfl-*12cq%p&d^^5^ac^o#+ag5f8_k&e^bk5-ku^m=9@"
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
  certbot-etc-letsencrypt:
  certbot-var-lib-letsencrypt:
  nginx_conf:
