# Generated by Django 4.1.3 on 2022-11-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='skills',
            name='logo',
        ),
        migrations.AddField(
            model_name='skills',
            name='logo_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
