# Generated by Django 4.1.3 on 2022-11-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_skills_options_remove_skills_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='logo_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
