# Generated by Django 4.1.4 on 2023-02-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_skills_logo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
